version: '3.3'


services:
  nginx:
    image: kensingtontech/nginx-jwt:latest
    #network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 192.168.0.105:80:80
