version: '3.3'


services:
  nginx:
    container_name: nginx_ex
    image: nginx:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 192.168.0.105:80:80
