version: '3.3'


services:
  live_sream:
    container_name: live_stream_container
    image: alqutami/rtmp-hls
    #image: alqutami/rtmp-hls:latest-alpine
    #volumes:
    #  - "./nginx2.conf:/etc/nginx/nginx.conf"
    ports:
      - 192.168.0.105:1935:1935
      - 192.168.0.105:8080:8080
